{% set version = "4.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-seurat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Seurat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Seurat/Seurat_{{ version }}.tar.gz
  sha256: 201aa96919b32378fc4cb67557188214c1242dcbae50cadd7d12c86666af8ace

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-kernsmooth
    - r-mass
    - r-matrix >=1.2_14
    - r-rann
    - r-rcolorbrewer
    - r-rocr
    - r-rcpp >=1.0.7
    - r-rcppannoy >=0.0.18
    - r-rcppeigen
    - r-rcppprogress
    - r-rtsne
    - r-seuratobject >=4.1.0
    - r-cluster
    - r-cowplot
    - r-fitdistrplus
    - r-future
    - r-future.apply
    - r-ggplot2 >=3.3.0
    - r-ggrepel
    - r-ggridges
    - r-httr
    - r-ica
    - r-igraph
    - r-irlba
    - r-jsonlite
    - r-leiden >=0.3.1
    - r-lmtest
    - r-matrixstats
    - r-miniui
    - r-patchwork
    - r-pbapply
    - r-plotly >=4.9.0
    - r-png
    - r-reticulate
    - r-rlang
    - r-scales
    - r-scattermore >=0.7
    - r-sctransform >=0.3.3
    - r-shiny
    - r-spatstat.core
    - r-spatstat.geom
    - r-tibble
    - r-uwot >=0.1.9
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-kernsmooth
    - r-mass
    - r-matrix >=1.2_14
    - r-rann
    - r-rcolorbrewer
    - r-rocr
    - r-rcpp >=1.0.7
    - r-rcppannoy >=0.0.18
    - r-rcppeigen
    - r-rcppprogress
    - r-rtsne
    - r-seuratobject >=4.1.0
    - r-cluster
    - r-cowplot
    - r-fitdistrplus
    - r-future
    - r-future.apply
    - r-ggplot2 >=3.3.0
    - r-ggrepel
    - r-ggridges
    - r-httr
    - r-ica
    - r-igraph
    - r-irlba
    - r-jsonlite
    - r-leiden >=0.3.1
    - r-lmtest
    - r-matrixstats
    - r-miniui
    - r-patchwork
    - r-pbapply
    - r-plotly >=4.9.0
    - r-png
    - r-reticulate
    - r-rlang
    - r-scales
    - r-scattermore >=0.7
    - r-sctransform >=0.3.3
    - r-shiny
    - r-spatstat.core
    - r-spatstat.geom
    - r-tibble
    - r-uwot >=0.1.9

test:
  commands:
    - $R -e "library('Seurat')"           # [not win]
    - "\"%R%\" -e \"library('Seurat')\""  # [win]

about:
  home: https://satijalab.org/seurat, https://github.com/satijalab/seurat
  license: MIT
  summary: A toolkit for quality control, analysis, and exploration of single cell RNA sequencing data. 'Seurat' aims to enable users to identify and interpret sources of heterogeneity from single cell transcriptomic measurements, and to integrate diverse types of single cell data. See Satija R, Farrell J, Gennert D, et
    al (2015) <doi:10.1038/nbt.3192>, Macosko E, Basu A, Satija R, et al (2015) <doi:10.1016/j.cell.2015.05.002>, and Stuart T, Butler A, et al (2019) <doi:10.1016/j.cell.2019.05.031> for more details.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
