travis:
  secure:
    BINSTAR_TOKEN: cUV23u8sdjl+CKe/wXP0f/Bx2znnsoZDukYfESUtRhe+w4lBbg0PDQcOrdq40EpchaCLTKuc4kOTYkR1X/9MJYiCM5/mIKT8Iyz9lC7CvafzNgStV/Q3mxuee6w6RppjqkjDe8O+b5leS6M5OPGeBL8u5ujtkjnIFR3aNUebctkzKy525FMqWy2+c7cUsYAo8285lRIv8wzpZSMTXbz1VLJ7WPnq/z7PzZ8Ukahd8nxH5GfKKIPpHnfUeZ64UEIxpZqXH8Yu2vxEKY4XggGo+jy/LCeUgUS4pmvDYReSQKLVhAcm2geGbQwlv2pPcIaj5Piwp5bUmMQ+cE+CErhEjakElefnblGwVGipSxxT3+O+uw1FFBqqrDhg6aXSHXYjYjU/n8sM9Gqj8nJ+1hHbSa4eHwh5rW9X0Rw6Pr4BY4vFab5CQoRWfUmDfhlZDZwXtqfbM/nbMnYPeV2VcVykTP7fwzXHS9lHsyb4b4ozGedfkKZvmjUtn01cT9bgmwzeVrJ1pEacBpbBIWUzVzVIAm6BwwLUlmmRXiUKLgqZgOJqaDseD1UPL6wmUEQSwkgS4W76vOxyGkj6ETjZfxUc3RN7YGusmjdfcpv5PxtTDE2v5QNwYyANTPeFD7blR36PYhEJG6fpPcylQ+kcqfQYVnJ79owRzZPDUy0xnJyKrZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
